# Generated by Django 3.2.16 on 2022-11-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221128_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='string',
            field=models.CharField(default='', max_length=7),
        ),
    ]
