# Generated by Django 3.2.16 on 2022-11-29 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0003_alter_game_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='asdd',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('string', models.CharField(default='', max_length=7)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
