# Generated by Django 3.2.16 on 2022-11-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_asdd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='string',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
